export enum ReasonCode {
  LOW_AMOUNT = "LOW_AMOUNT",
  MEDIUM_AMOUNT = "MEDIUM_AMOUNT",
  HIGH_AMOUNT = "HIGH_AMOUNT",
  UNKNOWN_DEVICE = "UNKNOWN_DEVICE",
  UNUSUAL_LOCATION = "UNUSUAL_LOCATION",
  NEW_BENEFICIARY = "NEW_BENEFICIARY",
  LOW_SESSION_TRUST = "LOW_SESSION_TRUST",
  MULTIPLE_RECENT_TRANSACTIONS = "MULTIPLE_RECENT_TRANSACTIONS",
  VELOCITY_PATTERN = "VELOCITY_PATTERN",
  STRUCTURED_AMOUNTS = "STRUCTURED_AMOUNTS",
  MULTIPLE_NEW_BENEFICIARIES = "MULTIPLE_NEW_BENEFICIARIES"
}