export enum RequiredAction {
  ALLOW = "ALLOW",
  SILENT_AUTH = "SILENT_AUTH",
  STRONG_AUTH_REQUIRED = "STRONG_AUTH_REQUIRED",
  HOLD_FOR_REVIEW = "HOLD_FOR_REVIEW",
  ACCOUNT_BLOCK = "ACCOUNT_BLOCK"
}